version: "3.5"
services:
  app:
    container_name: cafe_api
    image: cafe_app:1
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    container_name: cafe_mongo
    image: mongo:4.0
    ports:
      - 27018:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=cafe
    #   - MONGO_INITDB_ROOT_PASSWORD=efac
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
