version: "3.5"
services:
  mongo:
    container_name: cafe_mongo
    image: mongo:4.0
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=cafe
    #   - MONGO_INITDB_ROOT_PASSWORD=efac
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
