version: "3.5"
services:
  mongo:
    container_name: cafe_mongo
    image: mongo:4.0
    ports:
      - 27018:27017
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
